project_name = "test-757ec"
credentiels_name = "test.json"
project_region = "europe-west9"
gke_service_account = "485072204838-compute@developer.gserviceaccount.com"
vpc_name = "clea"
repo_id = "test"
repo_location = "europe-west9"